<a href="https://colab.research.google.com/github/manishcodespace/deeplearn-project/blob/maihttps/operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors and Basic Operations

In deep learning, data is typically represented as tensors. Tensors are multi-dimensional arrays, similar to NumPy arrays, but they can also be used on GPUs for accelerated computing. Let's demonstrate a basic mathematical operation using PyTorch, a popular deep learning framework.

In [1]:
# First, let's import the PyTorch library
import torch

In [2]:
# Create two sample tensors
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

print("Tensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)

Tensor A:
 tensor([[1, 2],
        [3, 4]])
Tensor B:
 tensor([[5, 6],
        [7, 8]])


In [4]:
# Perform a basic mathematical operation: addition
tensor_sum = tensor_a + tensor_b

print("\nResult of Tensor A + Tensor B:\n", tensor_sum)


Result of Tensor A + Tensor B:
 tensor([[ 6,  8],
        [10, 12]])
