<a href="https://colab.research.google.com/github/manishcodespace/deeplearn-project/blob/maihttps/ten_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#create New Tensor
import torch
mytensor = torch.tensor([1,2,3])
mytensor

tensor([1, 2, 3])

In [4]:
#create special tensor
zerotensor = torch.zeros(3,3)
zerotensor

onetensor = torch.ones(4,4)
onetensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
#create random tensor
randomtensor = torch.rand(3,3)
randomtensor

tensor([[0.8068, 0.7750, 0.5315],
        [0.2371, 0.1419, 0.8444],
        [0.2835, 0.3216, 0.9785]])

In [8]:
# reshape tensor
x = torch.tensor([1,2,3,4,5,6])
new_x = x.reshape(2, 3)
new_x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
import torch
mytorch3 = torch.arange(10);
mytorch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])